### ISSUE TITLE
Linux 下没有 certutil 无法运行

### ISSUE THREAD

**Issue by rubnet** [F-TD5X/SNI_Bypass#2]
运行 `go run main/main.go  -h 1 -log=""`
空指针退出
panic: runtime error: invalid memory address or [nil pointer dereference](https://github.com/F-TD5X/SNI_Bypass/blob/Go/core/certificate/certificate.go#L146)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x255440]

goroutine 1 [running]:
os/exec.(*Cmd).Output(0x0, 0x4000115050, 0x40001877d8, 0x2581b8, 0x4000162000, 0x0)
        /usr/local/go/src/os/exec/exec.go:535 +0x20
github.com/F-TD5X/SNI_Bypass/core/certificate.TrustCACert(0x34c400, 0x4000114180)
        /xxx/SNI_Bypass/core/certificate/certificate.go:146 +0x24
github.com/F-TD5X/SNI_Bypass/core/certificate.init.0()
        /xxx/SNI_Bypass/core/certificate/certificate.go:130 +0x164
exit status 2

**Comment by F-TD5X** [comment]
哦，linux cert 管理代码还没写，这段时间线下乱七八糟的事有点多，得过段时间更新了

**Comment by rubnet** [comment]
发现更好的替代工具
https://github.com/macronut/phantomsocks
